[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ragang"
version = "0.0.8b0"
description = "Ground-truth-free RAG evaluation and diagnosis framework"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "httpcore[asyncio]>=1.0.0",
    "numpy>=2.3.2",
    "pymilvus>=2.6.0",
    "pymupdf>=1.26.6",
    "requests>=2.32.4",
    "scikit-learn>=1.7.1",
    "scipy>=1.16.0",
    "websockets>=15.0.1",
]
authors = [
    {name = "Park-SeungWoo", email = "tmd24710@g.skku.edu"},
    {name = "Kim-YunTae", email = "unte2002@g.skku.edu"},
    {name = "Lee-JungWoo", email = "smartljw2004@g.skku.edu"},
    {name = "Jung-MoonGyu", email = "jmoongyu24@gmail.com"},
    {name = "Kim-JaeJun", email = "jaeiko@g.skku.edu"},
]
keywords = ["rag", "evaluation", "diagnosis", "llm", "graphrag"]

[project.scripts]
ragang = 'ragang.cli_script.entry:main'

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ['ragang*']

[tool.setuptools.package-data]
ragang = ['templates/**/*']

[tool.setuptools.exclude-package-data]
ragang = ['**/__pycache__/*', '**/*.pyc', '**/*.pyo']
