from common.bases.datas.performance_dataclass import Performance
from common.bases.abstracts.base_metric import BaseMetric
from adapters.llm_adapter import BaseLLMAdapter
from adapters.embedding_adapter import BaseEmbeddingAdapter
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
"""
Name : Generator faithfulness metric via Yes/No judgement on claims
Target : Answer-retrieval faithfulness
Type : Generator, LLM-as-a-judge, claim-based
Explanation : 생성한 답안을 claim 단위로 나누고 각 claim이 검색 문서를 기반으로 하는지 LLM에게 Yes/No를 답하게 하는 메트릭입니다. 최종 결과는 해당하는 claim 수 / 전체 claim 수 입니다.
"""
class A2RYNFaithfulnessMetric(BaseMetric):
    def __init__(self, llm_adapter : BaseLLMAdapter):
        self.llm_adapter = llm_adapter

    def evaluate(self, docs: list[str], gen: str) -> Performance:

        prompt_claim_generation = (   #todo : prompt needs to be refined. especially the rubric has to be specified more.
            """
            The following text is an answer generated by an LLM in response to a user question.

            Split the answer into **evaluation units**, where each unit represents a self-contained claim, explanation, or fact that can be **independently evaluated for factual accuracy or relevance**.

            Avoid splitting into single sentences unless necessary. If multiple sentences support the same point or explain a single concept, keep them together in one unit.

            Each unit should be meaningful and complete enough to be judged on its own.

            <Output format>
            1. Unit 1
            2. Unit 2
            ...
            n. Unit n

            <Example>
            Text:
            Large Language Models (LLMs) are trained on vast datasets composed of text from books, websites, and other sources. This training enables them to generate fluent and coherent responses. However, LLMs do not possess true understanding or consciousness. Instead, they rely on statistical patterns in language to predict likely next words. As a result, they can sometimes produce hallucinated or inaccurate content, especially on topics not well-covered in their training data.

            Output:
            1. Large Language Models (LLMs) are trained on vast datasets composed of text from books, websites, and other sources.  
            2. This training enables LLMs to generate fluent and coherent responses.  
            3. LLMs do not possess true understanding or consciousness; they rely on statistical patterns in language to predict likely next words.  
            4. Because of this, LLMs can sometimes produce hallucinated or inaccurate content, especially when the topic is not well covered in their training data.
            ---
            """
        )
        user_query = f"Text:\n{gen}\n\nOutput:\n"
        response = self.llm_adapter.request(prompt_claim_generation, user_query)
        claim_list = [line for line in response["text"].split('\n') if line.strip()]
        prompt_claim_judgement = (   #todo : prompt needs to be refined. especially the rubric has to be specified more.
            """
            You are given a single claim generated by an LLM, and a set of retrieved documents that were provided as context during generation.

            Your task is to determine whether the claim is **grounded** in the retrieved documents — that is, whether it can be supported by the content of any of the documents.

            Instructions:
            - If the claim is **explicitly stated or clearly supported** by one or more of the retrieved documents, mark it as **"Grounded"**.
            - If the claim is **not supported**, **contradicted**, or **cannot be verified** by any of the documents, mark it as **"Not Grounded"**.
            - Briefly justify your decision by citing matching or missing content from the documents.

            <Output format>
            Claim: [insert claim]

            Justification:
            [Explain whether the claim is supported by the content. If grounded, mention the relevant document(s) and excerpt(s). If not, explain what's missing or unsupported.]
            
            Groundedness: [Grounded / Not Grounded]

            <Example>

            Claim:
            "GPT-4 was released in March 2023."

            Retrieved Documents:
            1. "OpenAI released GPT-4 in March 2023, with improved reasoning performance."
            2. "Unlike earlier models, GPT-4 can process both text and images."

            Justification:
            The first document supports the release date of GPT-4.

            Groundedness: Grounded

            ---

            <Now your input>

            """
        )
        score = 0
        for claim in claim_list:
            print(f"Claim: {claim}")
            user_query = f"Claim:\n{claim}\n\nRetrieved Documents:{docs}\n\nJustification:\n"
            response = self.llm_adapter.request(prompt_claim_judgement, user_query)
            try:
                for line in reversed(response["text"].strip().splitlines()):
                    line = line.strip()
                    if line.startswith("Groundedness:"):
                        value = line.split(":", 1)[1].strip()
                        if value == "Grounded":
                            print("Grounded")
                            score += 1
                        else:
                            print("Not Grounded")
            except ValueError:
                score = 0.0  # Default to 0 if the response is not a valid form
        return Performance(score=score/len(claim_list), unit="", metric="Yes/No Relevancy")





"""
Name : Generator faithfulness metric via scoring on claims
Target : Answer-retrieval faithfulness
Type : Generator, LLM-as-a-judge, claim-based
Explanation : 생성한 답안을 claim 단위로 나누고 각 claim이 검색 문서를 기반으로 하는지를 LLM으로 채점하는 메트릭입니다. 최종 결과는 점수 합 / 최고 점수 입니다.
"""
class A2RSimpleScoringFaithfulnessMetric(BaseMetric):
    def __init__(self, llm_adapter : BaseLLMAdapter):
        self.llm_adapter = llm_adapter

    def evaluate(self, docs: list[str], gen: str) -> Performance:
        prompt_claim_generation = (
            """
            The following text is an answer generated by an LLM in response to a user question.

            Split the answer into **evaluation units**, where each unit represents a self-contained claim, explanation, or fact that can be **independently evaluated for factual accuracy or relevance**.

            Avoid splitting into single sentences unless necessary. If multiple sentences support the same point or explain a single concept, keep them together in one unit.

            Each unit should be meaningful and complete enough to be judged on its own.

            <Output format>
            1. Unit 1
            2. Unit 2
            ...
            n. Unit n

            <Example>
            Text:
            Large Language Models (LLMs) are trained on vast datasets composed of text from books, websites, and other sources. This training enables them to generate fluent and coherent responses. However, LLMs do not possess true understanding or consciousness. Instead, they rely on statistical patterns in language to predict likely next words. As a result, they can sometimes produce hallucinated or inaccurate content, especially on topics not well-covered in their training data.

            Output:
            1. Large Language Models (LLMs) are trained on vast datasets composed of text from books, websites, and other sources.  
            2. This training enables LLMs to generate fluent and coherent responses.  
            3. LLMs do not possess true understanding or consciousness; they rely on statistical patterns in language to predict likely next words.  
            4. Because of this, LLMs can sometimes produce hallucinated or inaccurate content, especially when the topic is not well covered in their training data.
            ---
            """
        )
        user_query = f"Text:\n{gen}\n\nOutput:\n"
        response = self.llm_adapter.request(prompt_claim_generation, user_query)
        claim_list = [line for line in response["text"].split('\n') if line.strip()]

        prompt_claim_scoring = (
            """
            You are given a single claim generated by an LLM and a set of retrieved documents that were provided as context. Your task is to score the faithfulness of the claim based on the provided documents.

            **Scoring Rubric:**
            - **4 (Exactly Aligns):** The claim is fully supported by the information in the retrieved documents.
            - **2 (Partially Aligns):** The claim is partially supported by the documents but may contain some minor inaccuracies or unverified details.
            - **0 (Does Not Align):** The claim is inaccurate, contradicted by the documents, or completely unrelated to the provided context.

            **Instructions:**
            1.  Carefully read the claim and the retrieved documents.
            2.  Compare the information in the claim against the documents.
            3.  Provide a brief justification for your score.
            4.  Assign a score of 0, 2, or 4 based on the rubric.

            **Output Format:**
            Claim: [The claim being evaluated]

            Justification:
            [Your brief explanation for the score]

            Score: [0, 2, or 4]

            **Example:**
            Claim:
            "GPT-4 was released by OpenAI in March 2023 and can process both text and images."

            Retrieved Documents:
            1. "OpenAI released GPT-4 in March 2023, with improved reasoning performance."
            2. "Unlike earlier models, GPT-4 can process both text and images."

            Justification:
            Both parts of the claim—the release date and the multimodal capability—are explicitly supported by the provided documents.

            Score: 4
            ---
            """
        )

        total_score = 0
        for i, claim in enumerate(claim_list):
            user_query = f"Claim:\n{claim}\n\nRetrieved Documents:{docs}\n\nJustification:\n"
            response = self.llm_adapter.request(prompt_claim_scoring, user_query)
            score = 0
            try:
                for line in reversed(response["text"].strip().splitlines()):
                    line = line.strip()
                    if line.startswith("Score:"):
                        value = line.split(":", 1)[1].strip()
                        score = int(value)
                        total_score += score
                        break
            except (ValueError, IndexError):
                # In case of parsing error, assume the worst score
                score = 0
            
            print(f"claim {i+1}: {claim} score: {score}")

        final_score = total_score / (len(claim_list) * 4) if claim_list else 0
        return Performance(score=final_score, unit="score", metric="Simple Scoring Faithfulness")
    

"""
Name : Generator hallucination metric via Yes/No judgement
Target : Answer-retrieval faithfulness
Type : Generator, LLM-as-a-judge
Explanation : 생성한 답안에 hallucination이 있는지 LLM에게 Yes/No를 답하게 하는 메트릭입니다. 최종 결과는 factual일 경우 1, hallucinated일 경우 0 입니다.
"""
class A2RHallucinationFaithfulnessMetric(BaseMetric):
    def __init__(self, llm_adapter: BaseLLMAdapter):
        self.llm_adapter = llm_adapter

    def evaluate(self, query: str, reference: list[str], gen: str) -> Performance:
        prompt = f"""In this task, you will be presented with a query, a reference text and an answer. 
            The answer is generated to the question based on the reference text. The answer may contain false information. 
            You must use the reference text to determine if the answer to the question contains false information, if the answer is a hallucination of facts. 
            Your objective is to determine whether the answer text contains factual information and is not a hallucination. 
            A 'hallucination' refers to an answer that is not based on the reference text or assumes information that is not available in the reference text. 
            Your response should be a single word: either "factual" or "hallucinated", and it should not include any other text or characters. 
            "hallucinated" indicates that the answer provides factually inaccurate information to the query based on the reference text. 
            "factual" indicates that the answer to the question is correct relative to the reference text, and does not contain made up information. 
            Please read the query and reference text carefully before determining your response.
            # Query: {query}
            # Reference text: {reference}
            # Answer: {gen}
            Is the answer above factual or hallucinated based on the query and reference text?"""

        response = self.llm_adapter.request(prompt, "")
        result = response["text"].strip().lower()

        score = 1 if result == "factual" else 0

        return Performance(score=score, unit="", metric="Hallucination (Factual/Hallucinated)")



"""
Name : Generator faithfulness metric via Yes/No judgement on claims
Target : Answer-retrieval faithfulness
Type : Generator, LLM-as-a-judge, claim-based
Explanation : 생성한 답안을 claim 단위로 나누고 각 claim이 검색 문서와 모순되는지 LLM에게 Yes/No를 답하게 하는 메트릭입니다. 최종 결과는 모순이 없는 claim 수 / 전체 claim 수 입니다.
"""
class A2RTruthfulFaithfulnessMetric(BaseMetric):
    def __init__(self, llm_adapter : BaseLLMAdapter):
        self.llm_adapter = llm_adapter

    def evaluate(self, docs: list[str], gen: str) -> Performance:

        prompt_claim_generation = (   #todo : prompt needs to be refined. especially the rubric has to be specified more.
            """
            The following text is an answer generated by an LLM in response to a user question.

            Split the answer into **evaluation units**, where each unit represents a self-contained claim, explanation, or fact that can be **independently evaluated for factual accuracy or relevance**.

            Avoid splitting into single sentences unless necessary. If multiple sentences support the same point or explain a single concept, keep them together in one unit.

            Each unit should be meaningful and complete enough to be judged on its own.

            <Output format>
            1. Unit 1
            2. Unit 2
            ...
            n. Unit n

            <Example>
            Text:
            Large Language Models (LLMs) are trained on vast datasets composed of text from books, websites, and other sources. This training enables them to generate fluent and coherent responses. However, LLMs do not possess true understanding or consciousness. Instead, they rely on statistical patterns in language to predict likely next words. As a result, they can sometimes produce hallucinated or inaccurate content, especially on topics not well-covered in their training data.

            Output:
            1. Large Language Models (LLMs) are trained on vast datasets composed of text from books, websites, and other sources.  
            2. This training enables LLMs to generate fluent and coherent responses.  
            3. LLMs do not possess true understanding or consciousness; they rely on statistical patterns in language to predict likely next words.  
            4. Because of this, LLMs can sometimes produce hallucinated or inaccurate content, especially when the topic is not well covered in their training data.
            ---
            """
        )
        user_query = f"Text:\n{gen}\n\nOutput:\n"
        response = self.llm_adapter.request(prompt_claim_generation, user_query)
        claim_list = [line for line in response["text"].split('\n') if line.strip()]
        prompt_claim_judgement = (   #todo : prompt needs to be refined. especially the rubric has to be specified more.
            """
            You are given a single claim generated by an LLM and a set of retrieved documents that were available during generation.

            Your task is to assess whether the claim is **truthful**, based on whether it **contradicts any facts** presented in the retrieved documents.

            Instructions:
            - A claim is considered **Truthful** if it does **not contradict any facts** in the retrieved documents.
            - A claim is **Not Truthful** if it directly contradicts, misrepresents, or states something clearly incompatible with the documents.
            - You do **not** need to verify that the documents explicitly support the claim — only that they **do not contradict** it.
            - Provide a brief justification based on the presence or absence of contradiction.

            <Output format>
            Claim: [insert claim]

            Justification:
            [State whether the claim contradicts anything in the documents. If it does not, say so. If it does, explain what and where.]

            Faithfulness: [Truthful / Not Truthful]

            <Example>

            Claim:
            "GPT-4 was released in March 2023."

            Retrieved Documents:
            1. "OpenAI released GPT-4 in March 2023, with improved reasoning performance."
            2. "Unlike earlier models, GPT-4 can process both text and images."

            Justification:
            The claim is consistent with the information in the first document and is not contradicted anywhere.

            Faithfulness: Truthful

            ---

            <Now your input>

            """

        )
        score = 0
        for claim in claim_list:
            print(f"Claim: {claim}")
            user_query = f"Claim:\n{claim}\n\nRetrieved Documents:{docs}\n\nJustification:\n"
            response = self.llm_adapter.request(prompt_claim_judgement, user_query)
            try:
                for line in reversed(response["text"].strip().splitlines()):
                    line = line.strip()
                    if line.startswith("Faithfulness:"):
                        value = line.split(":", 1)[1].strip()
                        if value == "Truthful":
                            print("Truthful")
                            score += 1
                        else:
                            print("Not Truthful")
            except ValueError:
                score = 0.0  # Default to 0 if the response is not a valid form
        return Performance(score=score/len(claim_list), unit="", metric="Yes/No Relevancy")

