from common.bases.datas.performance_dataclass import Performance
from common.bases.abstracts.base_metric import BaseMetric
from adapters.llm_adapter import BaseLLMAdapter
from adapters.embedding_adapter import BaseEmbeddingAdapter
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
"""
Name : Generator faithfulness metric via Yes/No judgement on claims
Target : Answer-retrieval faithfulness
Type : Generator, LLM-as-a-judge, claim-based
Explanation : 생성한 답안을 claim 단위로 나누고 각 claim이 검색 문서를 기반으로 하는지 LLM에게 Yes/No를 답하게 하는 메트릭입니다. 최종 결과는 해당하는 claim 수 / 전체 claim 수 입니다.
"""
class A2RYNRelevancyMetric(BaseMetric):
    def __init__(self, llm_adapter : BaseLLMAdapter):
        self.llm_adapter = llm_adapter

    def evaluate(self, docs: list[str], gen: str) -> Performance:

        prompt_claim_generation = (   #todo : prompt needs to be refined. especially the rubric has to be specified more.
            """
            The following text is an answer generated by an LLM in response to a user question.

            Split the answer into **evaluation units**, where each unit represents a self-contained claim, explanation, or fact that can be **independently evaluated for factual accuracy or relevance**.

            Avoid splitting into single sentences unless necessary. If multiple sentences support the same point or explain a single concept, keep them together in one unit.

            Each unit should be meaningful and complete enough to be judged on its own.

            <Output format>
            1. Unit 1
            2. Unit 2
            ...
            n. Unit n

            <Example>
            Text:
            Large Language Models (LLMs) are trained on vast datasets composed of text from books, websites, and other sources. This training enables them to generate fluent and coherent responses. However, LLMs do not possess true understanding or consciousness. Instead, they rely on statistical patterns in language to predict likely next words. As a result, they can sometimes produce hallucinated or inaccurate content, especially on topics not well-covered in their training data.

            Output:
            1. Large Language Models (LLMs) are trained on vast datasets composed of text from books, websites, and other sources.  
            2. This training enables LLMs to generate fluent and coherent responses.  
            3. LLMs do not possess true understanding or consciousness; they rely on statistical patterns in language to predict likely next words.  
            4. Because of this, LLMs can sometimes produce hallucinated or inaccurate content, especially when the topic is not well covered in their training data.
            ---
            """
        )
        user_query = f"Text:\n{gen}\n\nOutput:\n"
        response = self.llm_adapter.request(prompt_claim_generation, user_query)
        claim_list = [line for line in response["text"].split('\n') if line.strip()]
        prompt_claim_judgement = (   #todo : prompt needs to be refined. especially the rubric has to be specified more.
            """
            You are given a single claim generated by an LLM, and a set of retrieved documents that were provided as context during generation.

            Your task is to determine whether the claim is **grounded** in the retrieved documents — that is, whether it can be supported by the content of any of the documents.

            Instructions:
            - If the claim is **explicitly stated or clearly supported** by one or more of the retrieved documents, mark it as **"Grounded"**.
            - If the claim is **not supported**, **contradicted**, or **cannot be verified** by any of the documents, mark it as **"Not Grounded"**.
            - Briefly justify your decision by citing matching or missing content from the documents.

            <Output format>
            Claim: [insert claim]

            Justification:
            [Explain whether the claim is supported by the content. If grounded, mention the relevant document(s) and excerpt(s). If not, explain what's missing or unsupported.]
            
            Groundedness: [Grounded / Not Grounded]

            <Example>

            Claim:
            "GPT-4 was released in March 2023."

            Retrieved Documents:
            1. "OpenAI released GPT-4 in March 2023, with improved reasoning performance."
            2. "Unlike earlier models, GPT-4 can process both text and images."

            Justification:
            The first document supports the release date of GPT-4.

            Groundedness: Grounded

            ---

            <Now your input>

            """
        )
        score = 0
        for claim in claim_list:
            print(f"Claim: {claim}")
            user_query = f"Claim:\n{claim}\n\nRetrieved Documents:{docs}\n\nJustification:\n"
            response = self.llm_adapter.request(prompt_claim_judgement, user_query)
            try:
                for line in reversed(response["text"].strip().splitlines()):
                    line = line.strip()
                    if line.startswith("Groundedness:"):
                        value = line.split(":", 1)[1].strip()
                        if value == "Grounded":
                            print("Grounded")
                            score += 1
                        else:
                            print("Not Grounded")
            except ValueError:
                score = 0.0  # Default to 0 if the response is not a valid form
        return Performance(score=score/len(claim_list), unit="", metric="Yes/No Relevancy")